FileUtils: fix cast for musl build
building on `musl` fails with error
```
error: no matching function for call to 'getdents'
```
due to `dirent_buffer` being cast to `uint8_t *`

cast to `struct dirent *` to fix musl build

Closes: #5999
Signed-off-by: Pepper Gray <hello@peppergray.xyz>