switch to portable move_if_noexcept wrapper
building using libc++ fails with:

```
FEX/FEXCore/include/FEXCore/fextl/functional.h:55:21: error: static assertion failed due to requirement 'noexcept(this->internal = std::move(wrapped_lambda))': This implementation of std::function does not support implementing fextl::move_only_function
   55 |       static_assert(noexcept(internal = std::move(wrapped_lambda)), "This implementation of std::function "
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
FEX/Source/Common/AsyncNet.h:253:7: note: in instantiation of function template specialization 'fextl::move_only_function<fasio::post_callback (fasio::error)>::move_only_function<(lambda at /home/pepper/dev/ghrepos/FEX/Source/Common/AsyncNet.h:253:7)>' requested here
  253 |       [ServerFD = FD, &Reactor = Reactor, OnAccept = std::move(OnAccept)](error ec) mutable {
      |       ^
1 error generated.
```

This works with libstdc++ because its std::function converting
constructor and converting assignment are conditionally noexcept
based on whether the target can be initialized without throwing.

libc++ does not expose the same guarantee on the converting assignment
operator. In current libc++, the `std::function` overload is declared
without `_NOEXCEPT`.

The fix uses a function pointer in the case that the guaranty is not
provided directly from the standard library instead of working around
`std::function` behavior.

For the straight forward cases the reference is stored in `internal` for
the other case in `internal_invoker`. `internal_invoker` is initialized
with a reference to a static function that calls `internal`. In case
`internal` is used this ensures that it is invoked accordingly, in case
`internal_invoker` is used, writing to it overrides the default behavior.
The choice which one to invoke is therefore branchless.

fix: #5474
Signed-off-by: Pepper Gray <hello@peppergray.xyz>